# Generated by Django 2.2.10 on 2020-03-05 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blacklistApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blackclient',
            options={'ordering': ['phone'], 'verbose_name': 'BlackКлиент', 'verbose_name_plural': 'BlackКлиенты'},
        ),
        migrations.CreateModel(
            name='AbonentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
