# Generated by Django 2.2.10 on 2020-03-05 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blacklistApp', '0002_auto_20200305_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackclient',
            name='abonentThatAdded',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
