# Generated by Django 2.2.10 on 2020-03-06 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blacklistApp', '0003_blackclient_abonentthatadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackclient',
            name='abonentThatAdded',
        ),
        migrations.AddField(
            model_name='blackclient',
            name='abonent_added',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
