# Generated by Django 2.2.10 on 2020-03-10 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blacklistApp', '0006_auto_20200306_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackclient',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='blackclient',
            name='abonent_added',
        ),
        migrations.AddField(
            model_name='blackclient',
            name='abonent_added',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
