# Generated by Django 2.2.10 on 2020-03-10 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacklistApp', '0008_auto_20200310_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bclient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blacklistApp.BlackClient'),
        ),
    ]
