# Generated by Django 2.2.10 on 2020-03-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklistApp', '0009_comment_bclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blackclient',
            name='tags_added',
            field=models.ManyToManyField(to='blacklistApp.Tags'),
        ),
    ]
